apiVersion: v1
kind: Service
metadata:
  name: back
  labels:
    app: back
spec:
  selector:
    app: back
  ports:
    - protocol: TCP
      port: 8080  # 서비스가 노출하는 포트 (외부에서 접근할 포트)
      targetPort: 8080  # 컨테이너 포트 (서비스가 내부적으로 연결할 포트)
  type: ClusterIP
